---
name: Gazpar_2_Mqtt
version: dev
slug: meterstoha
description: MetersToHA add-on for Home Assistant
url: https://github.com/vingerha/gazpar_2_mqtt
GRDF_USERNAME: username #your GRDF login (ex : myemail@email.com)
GRDF_PASSWORD: password #your GRDF password
MQTT_HOST: 127.0.0.1 #hostname or ip adress of the MQTT broker.
# OPTIONAL VARIABLES : see https://github.com/vingerha/gazpar_2_mqtt
