---
name: Gazpar_2_Mqtt
version: dev
slug: gazpar_2_mqtt
description: Gazpar_2_Mqtt add-on for Home Assistant
url: https://github.com/vingerha/gazpar_2_mqtt
map:
  - addon_config:rw
  - homeassistant_config
init: false
arch:
  - arm64
  - amd64
  - armv7
options:
  log_level: info
schema:
  GRDF_USERNAME: str
  GRDF_PASSWORD: str
  MQTT_HOST: str
image: vingerha/gazpar_2_mqtt
